defaults:
  - lr: step

seed: 0
logging: True

checkpoint: "bert-base-uncased"
max_epochs: 15
learning_rate: 0.00001
batch_size: 32
accumulation_steps: 4
gpus: 1
weight_decay: 0.0
lambda_weight: 1.0
explanation_regularization: True
label_count: 5

run:
  train_model: False
  test_model: False

data:
  generate_explanations: True
  save_explanations: True
  load_explanations: False
  teacher_path: "/home/wyatt/projects/bert_sst5_lightning/teacher.pth"
  eval_csv_path: "/home/wyatt/projects/bert_sst5_lightning/explanations/eval_explanations.csv"
  test_csv_path: "/home/wyatt/projects/bert_sst5_lightning/explanations/test_explanations.csv"
  train_csv_path: "/home/wyatt/projects/bert_sst5_lightning/explanations/train_explanations.csv"